FROM openjdk:8
MAINTAINER Cristhian Parra <cdparra@gmail.com>
ENV PROJECT_HOME /home/appcivist/production/appcivist-platform
ADD docker_confs/deploy-dev.sh deploy.sh
RUN chmod 777 deploy.sh
EXPOSE 9000
EXPOSE 8888
EXPOSE 9999
CMD bash deploy.sh
