version: "2"
services:
    appcivist-plataform:
      build:
          context: .
          dockerfile: Dockerfile-dev
      ports:
        - "9000:9000"
      volumes:
      - .:/home/appcivist/production/appcivist-platform
      - ./environment:/environment
      stdin_open: true
      env_file: .env
      depends_on:
      - db
    db:
      image: socialappslabberkeley/appcivist-db
      volumes:
      - /var/lib/postgresql/data2:/var/lib/postgresql/data
      - ./environment:/environment
      ports:
        - "5433:5432"
      env_file: .env

