package models;

/**
 * Created by ggaona on 16/8/17.
 */
public  class EventKeys {
    public static String NEW_CAMPAIGN = "NEW_CAMPAIGN";
    public static String NEW_WORKING_GROUP= "NEW_WORKING_GROUP";
    public static String NEW_VOTING_BALLOT= "NEW_VOTING_BALLOT";
    public static String NEW_MILESTONE= "NEW_MILESTONE";
    public static String NEW_CONTRIBUTION_IDEA= "NEW_CONTRIBUTION_IDEA";
    public static String NEW_CONTRIBUTION_PROPOSAL= "NEW_CONTRIBUTION_PROPOSAL";
    public static String NEW_CONTRIBUTION_DISCUSSION= "NEW_CONTRIBUTION_DISCUSSION";
    public static String NEW_CONTRIBUTION_COMMENT= "NEW_CONTRIBUTION_COMMENT";
    public static String NEW_CONTRIBUTION_NOTE= "NEW_CONTRIBUTION_NOTE";
    public static String NEW_CONTRIBUTION_FORUM_POST= "NEW_CONTRIBUTION_FORUM_POST";
    public static String NEW_CONTRIBUTION_FEEDBACK= "NEW_CONTRIBUTION_FEEDBACK";
    public static String NEW_CONTRIBUTION_FEEDBACK_FLAG= "NEW_CONTRIBUTION_FEEDBACK_FLAG";
    public static String NEW_CONTRIBUTION_ISSUE= "NEW_CONTRIBUTION_ISSUE";
    public static String UPDATED_ASSEMBLY= "UPDATED_ASSEMBLY";
    public static String UPDATED_ASSEMBLY_CONFIGS= "UPDATED_ASSEMBLY_CONFIGS";
    public static String UPDATED_CAMPAIGN= "UPDATED_CAMPAIGN";
    public static String UPDATED_CAMPAIGN_CONFIGS= "UPDATED_CAMPAIGN_CONFIGS";
    public static String UPDATED_WORKING_GROUP= "UPDATED_WORKING_GROUP";
    public static String UPDATED_WORKING_GROUP_CONFIGS= "UPDATED_WORKING_GROUP_CONFIGS";
    public static String UPDATED_VOTING_BALLOT= "UPDATED_VOTING_BALLOT";
    public static String UPDATED_MILESTONE= "UPDATED_MILESTONE";
    public static String UPDATED_CONTRIBUTION_IDEA= "UPDATED_CONTRIBUTION_IDEA";
    public static String UPDATED_CONTRIBUTION_PROPOSAL= "UPDATED_CONTRIBUTION_PROPOSAL";
    public static String UPDATED_CONTRIBUTION_DISCUSSION= "UPDATED_CONTRIBUTION_DISCUSSION";
    public static String UPDATED_CONTRIBUTION_COMMENT= "UPDATED_CONTRIBUTION_COMMENT";
    public static String UPDATED_CONTRIBUTION_NOTE= "UPDATED_CONTRIBUTION_NOTE";
    public static String UPDATED_CONTRIBUTION_FORUM_POST= "UPDATED_CONTRIBUTION_FORUM_POST";
    public static String UPDATED_CONTRIBUTION_FEEDBACK= "UPDATED_CONTRIBUTION_FEEDBACK";
    public static String UPDATED_CONTRIBUTION_HISTORY= "UPDATED_CONTRIBUTION_HISTORY";
    public static String MILESTONE_UPCOMING= "MILESTONE_UPCOMING";
    public static String MILESTONE_UPCOMING_IN_A_WEEK= "MILESTONE_UPCOMING_IN_A_WEEK";
    public static String MILESTONE_UPCOMING_IN_A_DAY= "MILESTONE_UPCOMING_IN_A_DAY";
    public static String MEMBER_JOINED= "MEMBER_JOINED";
    public static String DELETED_CONTRIBUTION= "DELETED_CONTRIBUTION";
    public static String MODERATED_CONTRIBUTION= "MODERATED_CONTRIBUTION";
}
