package enums;

public enum AppcivistNotificationTypes {
	UPCOMING_MILESTONE,
	ASSEMBLY_UPDATE,
	CAMPAIGN_UPDATE,
	WORKING_GROUP_UPDATE,
	CONTRIBUTION_UPDATE,
	PRIVATE_MESSAGE,
	FOLLOWED_ASSEMBLY_UPDATE,
	FOLLOWED_CAMPAIGN_UPDATE
}
